name = "shici-cloud"
main = "worker.js"
compatibility_date = "2026-06-08"

[vars]
FRONTEND_ORIGIN = "https://wayne718-afk.github.io"
FRONTEND_PATH = "/cet6-vocabulary/"

[[d1_databases]]
binding = "DB"
database_name = "shici-cloud"
database_id = "4cce5fc8-ac41-4878-a092-782de119b283"
